### ISSUE TITLE
ssh-agent test will fail if ssh is not started in bhyve

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ix-tests#28]
This test fails if sshd service is not started on the running host.

https://builds.ixsystems.com/jenkins/view/QA%20Tests/view/All/job/FreeNAS%20-%20Master%20-%20QA%20Tests/1668/testReport/ixbuild.resty.functional.create/ssh/Ensure_that_we_have_a_running_ssh_agent/

This is due to the fact ssh_agent cannot be started without the ssh service.  We need to find a way to skip this test when sshd service is not running.

See this for one example of how to skip using the framework: 

https://github.com/iXsystems/ixbuild/blob/3e327ec54c119a1363f7f8b13a1552c8b9fee373/freenas/9.10-tests/create/ntp

**Comment by pkgdemon** [comment]
We need to find out why this is failing, and what needs to be started in order for it to work.

Running 1 - Create - SSH Tests (4/5) - Ensure that we have a running ssh-agent - FAILED
Failed on test module: ssh

**Comment by pkgdemon** [comment]
The ssh-agent failure will also cause tests like this to fail.

Running 1 - Update - Cron tests (1/4) - Verify cronjob has created the test file..Could not open a connection to your authentication agent.
root@10.231.2.66's password:

**Comment by pkgdemon** [comment]
Please make necessary changes to feature-bhyve branch, and not master.  

https://github.com/iXsystems/ixbuild/tree/feature-bhyve

**Comment by pkgdemon** [comment]
Source code for the failing test is here:

https://github.com/iXsystems/ixbuild/blob/feature-bhyve/freenas/9.10-tests/create/ssh

**Comment by pkgdemon** [comment]
This triggers the issue locally when running sudo:

[jmaloney@joe-desktop] ~% sudo ssh-add -L
Password:
Sorry, try again.
Password:
Could not open a connection to your authentication agent.

**Comment by ericbsd** [comment]
Oh, this is finally done.
